Adds NCDs from ART Access visit
METS-Programme/openmrs-module-ugandaemr-sync pull request #143
Opened 2024-02-29 07:37 UTC by semujju

2024-03-02 07:50 UTC, slubwama requested changes

2024-03-02 07:50 UTC, slubwama commented on api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveVisitsDataFromARTAccessTask.java
> +               System.out.println(no_of_days);
Remove print and use log

2024-03-02 07:50 UTC, slubwama commented on api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveVisitsDataFromARTAccessTask.java
> +             System.out.println("print-results-1");
log instead of print

2024-03-02 07:50 UTC, slubwama commented on api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveVisitsDataFromARTAccessTask.java
> +            System.out.println(regimen);
same here

2024-03-02 07:50 UTC, slubwama commented on api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveVisitsDataFromARTAccessTask.java
> +            System.out.println("print-results-7");
same here

2024-03-02 07:50 UTC, slubwama commented on api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveVisitsDataFromARTAccessTask.java
> +            if (diabetesMeds.contains("Glibenclamide 5mg")) {
User codes instead of names

2024-03-02 07:50 UTC, slubwama commented on api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveVisitsDataFromARTAccessTask.java
> +            if (hypertensionMeds.contains("Amlodipine 10mg")) {
Use codes instead of names

2024-03-02 07:50 UTC, slubwama commented on api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveVisitsDataFromARTAccessTask.java
> +        System.out.println("print-results");
log instead of print

2024-03-27 08:16 UTC, semujju commented on api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveVisitsDataFromARTAccessTask.java
> +               System.out.println(no_of_days);
This is noted

2024-06-06 05:29 UTC, closed without merging