U4X-728: Delete unused tasks from UgandaEMR
METS-Programme/openmrs-module-ugandaemr-sync pull request #181
Opened 2024-10-31 11:59 UTC by semujju

https://metsprogramme.atlassian.net/browse/U4X-728?atlOrigin=eyJpIjoiMTk1MWI1YzA3ZjZmNGM2MWFlODY4N2ZjNDM5MjhlMTEiLCJwIjoiaiJ9

2024-10-31 12:13 UTC, slubwama requested changes
Is this the only task to delete in sync

2024-10-31 12:13 UTC, slubwama commented on api/src/main/resources/liquibase.xml
> -
Besides deleting these in liquibase have you considered also removing the classes which support the task

2024-10-31 12:18 UTC, semujju commented on api/src/main/resources/liquibase.xml
> -
There are no classes related to those tasks

2024-10-31 12:19 UTC, semujju commented on api/src/main/resources/liquibase.xml
> -
@slubwama thats the only task t delete in sync

2024-11-01 06:04 UTC, slubwama approved these changes

2024-11-01 06:04 UTC, merged