WIP: Pulling Data from ARTAccess To UgandaEMR
METS-Programme/openmrs-module-ugandaemr-sync pull request #52
Opened 2021-07-19 07:23 UTC by dbaluku

2021-09-13 13:10 UTC, slubwama requested changes

2021-09-13 13:10 UTC, slubwama commented on api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveVisitsDataFromARTAccessTask.java
> +        String ARTAccessServerUrlEndPoint="";
Camel Case this Variable

2021-09-13 13:10 UTC, slubwama commented on api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveVisitsDataFromARTAccessTask.java
> +    EncounterType ARTCardEncounterType = encounterService.getEncounterTypeByUuid("8d5b2be0-c2cc-11de-8d13-0010c6dffd0f");
Camel Case this Variable

2021-09-13 18:10 UTC, dbaluku commented on api/src/main/java/org/openmrs/module/ugandaemrsync/api/UgandaEMRHttpURLConnection.java
> +import javax.net.ssl.*;
Done

2021-09-13 18:10 UTC, dbaluku commented on api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveVisitsDataFromARTAccessTask.java
> +        String ARTAccessServerUrlEndPoint="";
Done

2021-09-13 18:11 UTC, dbaluku commented on api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveVisitsDataFromARTAccessTask.java
> +    EncounterType ARTCardEncounterType = encounterService.getEncounterTypeByUuid("8d5b2be0-c2cc-11de-8d13-0010c6dffd0f");
Done

2021-09-14 03:39 UTC, slubwama approved these changes

2021-09-20 05:35 UTC, slubwama commented
@dbaluku resolve conflicts

2021-09-20 14:08 UTC, slubwama commented on api/src/main/java/org/openmrs/module/ugandaemrsync/api/UgandaEMRHttpURLConnection.java
> +    public String getJson(String url) {
@dbaluku why did you introduce this.

2021-09-20 14:08 UTC, slubwama commented on api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveVisitsDataFromARTAccessTask.java
> +            results = ugandaEMRHttpURLConnection.getJson(artAccessServerUrlEndPoint);
@dbaluku how are you taking care of authentication

2021-09-20 15:27 UTC, dbaluku commented on api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveVisitsDataFromARTAccessTask.java
> +            results = ugandaEMRHttpURLConnection.getJson(artAccessServerUrlEndPoint);
@slubwama the endpoint was open with no authentication

2021-09-20 15:34 UTC, dbaluku commented on api/src/main/java/org/openmrs/module/ugandaemrsync/api/UgandaEMRHttpURLConnection.java
> +    public String getJson(String url) {
Is there a similar function

2021-09-21 04:30 UTC, slubwama commented on api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveVisitsDataFromARTAccessTask.java
> +            results = ugandaEMRHttpURLConnection.getJson(artAccessServerUrlEndPoint);
@dbaluku you always have to factor authentication in mind. Even when what you are testing with doesn't. 
We will be using HIM which requires either basic or token based.

2021-09-22 05:48 UTC, slubwama commented on api/src/main/java/org/openmrs/module/ugandaemrsync/api/UgandaEMRHttpURLConnection.java
> +    public Map getByWithBasicAuth(String url, String username, String password, String resultType) throws Exception {
@dbaluku why are you changing the method signature. did you consider other possible use in and out of this module??

2021-09-25 08:06 UTC, slubwama commented on api/src/main/java/org/openmrs/module/ugandaemrsync/api/UgandaEMRHttpURLConnection.java
> +                httpGet.addHeader("x-ugandaemr-facilityname", syncGlobalProperties.getGlobalProperty(GP_FACILITY_NAME));
Make sure even without authentication the headers can be sent

2021-09-25 11:33 UTC, slubwama commented
@dbaluku remove WIP from PR Name

2021-09-27 09:08 UTC, merged